### ISSUE TITLE
AssertionError: Norm type 'in' not support.

### ISSUE THREAD

**Issue by Hbroda** [chaofengc/Face-SPARNet#15]
Hi there!
When I try to test an image I get the following error.

======> Loading images, crop and align faces.
======> Saving aligned LQ faces to test_hzgg_results\LQ_faces
Traceback (most recent call last):
  File "test_enhance_single_unalign.py", line 105, in <module>
    enhance_model = def_models(opt)
  File "test_enhance_single_unalign.py", line 50, in def_models
    model = create_model(opt)
  File "F:\Anaconda3\Face-SPARNet-master\models\__init__.py", line 65, in create_model
    instance = model(opt)
  File "F:\Anaconda3\Face-SPARNet-master\models\sparnethd_model.py", line 26, in __init__
    res_depth=opt.res_depth, norm_type=opt.Gnorm, att_name=opt.att_name, bottleneck_size=opt.bottleneck_size)
  File "F:\Anaconda3\Face-SPARNet-master\models\sparnet.py", line 44, in __init__
    self.encoder.append(ResidualBlock(cin, cout, scale='down', hg_depth=hg_depth, att_name=att_name, **nrargs))
  File "F:\Anaconda3\Face-SPARNet-master\models\blocks.py", line 119, in __init__
    NormLayer(c_in, norm_type=self.norm_type),
  File "F:\Anaconda3\Face-SPARNet-master\models\blocks.py", line 30, in __init__
    assert 1==0, 'Norm type {} not support.'.format(norm_type)
AssertionError: Norm type 'in' not support.

Any idea why it is?

![Sin título](https://user-images.githubusercontent.com/87241145/127570836-126b1cad-6fe5-4591-8fe8-04851198ac08.png)

**Comment by chaofengc** [comment]
Current codes are only tested on Ubuntu. This is likely because command line in windows are parsed in a different way. You may try to use double quote or hard code the default options in files under `options/` directory.
